import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider";
import { authOptions } from "./api/auth/[...nextauth]/route";
import NextTopLoader from "nextjs-toploader";
import FirebaseAuthProvider from "./components/FirebaseAuthProvider";
import SubscriptionProvider from "./components/SubscriptionProvider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <NextTopLoader color="#D2DE32" showSpinner={false} />
        <SessionProvider session={session}>
          <FirebaseAuthProvider>
            <SubscriptionProvider>
              <header className=" bg-primary-foreground">
                <Navbar />
              </header>
              {children}
            </SubscriptionProvider>
          </FirebaseAuthProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
